### ISSUE TITLE
Create page with fullscreen map provided by mapbox

### ISSUE THREAD

**Issue by tboychuk** [bobocode-labs/gojohnny-ui#1]
* configure **appropriate react page**
* configure mapbox **map** using the following credentials:
  * access token: `pk.eyJ1IjoiYm95NHVjayIsImEiOiJkWlgxdVhRIn0.nzy-n4qIL6QNPiWtTO_UTw`
  * style url: `mapbox://styles/boy4uck/cj8795w2h3c5k2qs6sq35cu9z`

Mapbox docs: https://www.mapbox.com/mapbox-gl-js/api/

**Comment by omgkanamikun** [comment]
how to add mapbox into react
for render we use lib 
https://www.npmjs.com/package/react-mapbox-gl

**Comment by tboychuk** [comment]
Blocked by #15
